version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest coverage
      - run: python Minesweeper.py
  test:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest coverage
      - run:
          name: Run unit tests
          command: pytest test.py
      - run:
          name: Generate coverage report
          command: coverage run --source=Minesweeper.py -m pytest test.py && coverage report

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
