version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run: pip install pytest
      - run: pip install coverage
      - run: python Minesweeper.py
  test:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run: pip install pytest
      - run: pip install coverage
      - run: pytest test.py
      - run:
          name: Generate coverage report
          command: |
            pip install coverage
            coverage run --source=Minesweeper.py -m pytest test.py
            coverage report

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
